"""empty message

Revision ID: 1073dc28e145
Revises: 386849dea26f
Create Date: 2026-06-10 14:08:38.016478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1073dc28e145'
down_revision = '386849dea26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_token', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.drop_column('approval_token')

    # ### end Alembic commands ###
