"""added report log

Revision ID: 386849dea26f
Revises: 085ee03e7241
Create Date: 2026-06-10 10:40:24.905120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386849dea26f'
down_revision = '085ee03e7241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('advanced_by', sa.String(length=100), nullable=False),
    sa.Column('curr_stage', sa.String(length=100), nullable=False),
    sa.Column('next_stage', sa.String(length=100), nullable=False),
    sa.Column('advanced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['requester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_log')
    # ### end Alembic commands ###
