"""empty message

Revision ID: 96821288a9a3
Revises: d27f922849dd
Create Date: 2026-06-16 17:09:20.556239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96821288a9a3'
down_revision = 'd27f922849dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_otp',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_assignee', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.drop_column('current_assignee')

    op.drop_table('login_otp')
    # ### end Alembic commands ###
