"""empty message

Revision ID: 9e5571418889
Revises: 1073dc28e145
Create Date: 2026-06-11 10:32:22.652523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e5571418889'
down_revision = '1073dc28e145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.String(length=64), nullable=False))
        batch_op.drop_column('request_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
