"""empty message

Revision ID: d133aa913ad5
Revises: 96821288a9a3
Create Date: 2026-06-25 16:03:50.202130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd133aa913ad5'
down_revision = '96821288a9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requester_current_assignee'), ['current_assignee'], unique=False)
        batch_op.create_index(batch_op.f('ix_requester_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requester_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requester', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requester_status'))
        batch_op.drop_index(batch_op.f('ix_requester_request_type'))
        batch_op.drop_index(batch_op.f('ix_requester_current_assignee'))

    # ### end Alembic commands ###
