"""empty message

Revision ID: d27f922849dd
Revises: 9e5571418889
Create Date: 2026-06-16 10:23:17.430661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f922849dd'
down_revision = '9e5571418889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_log', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
